apiVersion: v1
kind: Service
metadata:
  name: e-commence-fe-service
spec:
  selector:
    app: e-commence-fe
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
      nodePort: 30019
    - name: https
      port: 4430
      targetPort: 4430
      protocol: TCP
      nodePort: 30020
    - name: quic
      port: 4430
      targetPort: 4430
      protocol: UDP
      nodePort: 30021
  type: NodePort
