apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-web
  labels:
    app: simple-bank-web
spec:
  template:
    spec:
      containers:
        - name: simple-bank-web
          resources:
            limits:
              memory: "200Mi"
              cpu: "200m"

