/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ProfileIndexLazyImport = createFileRoute('/profile/')()
const ProductsIndexLazyImport = createFileRoute('/products/')()
const OrdersIndexLazyImport = createFileRoute('/orders/')()
const LogoutIndexLazyImport = createFileRoute('/logout/')()
const LoginIndexLazyImport = createFileRoute('/login/')()
const CreditcardsIndexLazyImport = createFileRoute('/credit_cards/')()
const CheckoutIndexLazyImport = createFileRoute('/checkout/')()
const CartsIndexLazyImport = createFileRoute('/carts/')()
const CardsIndexLazyImport = createFileRoute('/cards/')()
const CallbackIndexLazyImport = createFileRoute('/callback/')()
const BalanceIndexLazyImport = createFileRoute('/balance/')()
const AddressesIndexLazyImport = createFileRoute('/addresses/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ProfileIndexLazyRoute = ProfileIndexLazyImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile/index.lazy').then((d) => d.Route))

const ProductsIndexLazyRoute = ProductsIndexLazyImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/products/index.lazy').then((d) => d.Route),
)

const OrdersIndexLazyRoute = OrdersIndexLazyImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/orders/index.lazy').then((d) => d.Route))

const LogoutIndexLazyRoute = LogoutIndexLazyImport.update({
  id: '/logout/',
  path: '/logout/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/logout/index.lazy').then((d) => d.Route))

const LoginIndexLazyRoute = LoginIndexLazyImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))

const CreditcardsIndexLazyRoute = CreditcardsIndexLazyImport.update({
  id: '/credit_cards/',
  path: '/credit_cards/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/credit_cards/index.lazy').then((d) => d.Route),
)

const CheckoutIndexLazyRoute = CheckoutIndexLazyImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/checkout/index.lazy').then((d) => d.Route),
)

const CartsIndexLazyRoute = CartsIndexLazyImport.update({
  id: '/carts/',
  path: '/carts/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/carts/index.lazy').then((d) => d.Route))

const CardsIndexLazyRoute = CardsIndexLazyImport.update({
  id: '/cards/',
  path: '/cards/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cards/index.lazy').then((d) => d.Route))

const CallbackIndexLazyRoute = CallbackIndexLazyImport.update({
  id: '/callback/',
  path: '/callback/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/callback/index.lazy').then((d) => d.Route),
)

const BalanceIndexLazyRoute = BalanceIndexLazyImport.update({
  id: '/balance/',
  path: '/balance/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/balance/index.lazy').then((d) => d.Route))

const AddressesIndexLazyRoute = AddressesIndexLazyImport.update({
  id: '/addresses/',
  path: '/addresses/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/addresses/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/addresses/': {
      id: '/addresses/'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/balance/': {
      id: '/balance/'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof BalanceIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/callback/': {
      id: '/callback/'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cards/': {
      id: '/cards/'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/carts/': {
      id: '/carts/'
      path: '/carts'
      fullPath: '/carts'
      preLoaderRoute: typeof CartsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/credit_cards/': {
      id: '/credit_cards/'
      path: '/credit_cards'
      fullPath: '/credit_cards'
      preLoaderRoute: typeof CreditcardsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/logout/': {
      id: '/logout/'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/addresses': typeof AddressesIndexLazyRoute
  '/balance': typeof BalanceIndexLazyRoute
  '/callback': typeof CallbackIndexLazyRoute
  '/cards': typeof CardsIndexLazyRoute
  '/carts': typeof CartsIndexLazyRoute
  '/checkout': typeof CheckoutIndexLazyRoute
  '/credit_cards': typeof CreditcardsIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/logout': typeof LogoutIndexLazyRoute
  '/orders': typeof OrdersIndexLazyRoute
  '/products': typeof ProductsIndexLazyRoute
  '/profile': typeof ProfileIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/addresses': typeof AddressesIndexLazyRoute
  '/balance': typeof BalanceIndexLazyRoute
  '/callback': typeof CallbackIndexLazyRoute
  '/cards': typeof CardsIndexLazyRoute
  '/carts': typeof CartsIndexLazyRoute
  '/checkout': typeof CheckoutIndexLazyRoute
  '/credit_cards': typeof CreditcardsIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/logout': typeof LogoutIndexLazyRoute
  '/orders': typeof OrdersIndexLazyRoute
  '/products': typeof ProductsIndexLazyRoute
  '/profile': typeof ProfileIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/addresses/': typeof AddressesIndexLazyRoute
  '/balance/': typeof BalanceIndexLazyRoute
  '/callback/': typeof CallbackIndexLazyRoute
  '/cards/': typeof CardsIndexLazyRoute
  '/carts/': typeof CartsIndexLazyRoute
  '/checkout/': typeof CheckoutIndexLazyRoute
  '/credit_cards/': typeof CreditcardsIndexLazyRoute
  '/login/': typeof LoginIndexLazyRoute
  '/logout/': typeof LogoutIndexLazyRoute
  '/orders/': typeof OrdersIndexLazyRoute
  '/products/': typeof ProductsIndexLazyRoute
  '/profile/': typeof ProfileIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addresses'
    | '/balance'
    | '/callback'
    | '/cards'
    | '/carts'
    | '/checkout'
    | '/credit_cards'
    | '/login'
    | '/logout'
    | '/orders'
    | '/products'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addresses'
    | '/balance'
    | '/callback'
    | '/cards'
    | '/carts'
    | '/checkout'
    | '/credit_cards'
    | '/login'
    | '/logout'
    | '/orders'
    | '/products'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/addresses/'
    | '/balance/'
    | '/callback/'
    | '/cards/'
    | '/carts/'
    | '/checkout/'
    | '/credit_cards/'
    | '/login/'
    | '/logout/'
    | '/orders/'
    | '/products/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AddressesIndexLazyRoute: typeof AddressesIndexLazyRoute
  BalanceIndexLazyRoute: typeof BalanceIndexLazyRoute
  CallbackIndexLazyRoute: typeof CallbackIndexLazyRoute
  CardsIndexLazyRoute: typeof CardsIndexLazyRoute
  CartsIndexLazyRoute: typeof CartsIndexLazyRoute
  CheckoutIndexLazyRoute: typeof CheckoutIndexLazyRoute
  CreditcardsIndexLazyRoute: typeof CreditcardsIndexLazyRoute
  LoginIndexLazyRoute: typeof LoginIndexLazyRoute
  LogoutIndexLazyRoute: typeof LogoutIndexLazyRoute
  OrdersIndexLazyRoute: typeof OrdersIndexLazyRoute
  ProductsIndexLazyRoute: typeof ProductsIndexLazyRoute
  ProfileIndexLazyRoute: typeof ProfileIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AddressesIndexLazyRoute: AddressesIndexLazyRoute,
  BalanceIndexLazyRoute: BalanceIndexLazyRoute,
  CallbackIndexLazyRoute: CallbackIndexLazyRoute,
  CardsIndexLazyRoute: CardsIndexLazyRoute,
  CartsIndexLazyRoute: CartsIndexLazyRoute,
  CheckoutIndexLazyRoute: CheckoutIndexLazyRoute,
  CreditcardsIndexLazyRoute: CreditcardsIndexLazyRoute,
  LoginIndexLazyRoute: LoginIndexLazyRoute,
  LogoutIndexLazyRoute: LogoutIndexLazyRoute,
  OrdersIndexLazyRoute: OrdersIndexLazyRoute,
  ProductsIndexLazyRoute: ProductsIndexLazyRoute,
  ProfileIndexLazyRoute: ProfileIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/addresses/",
        "/balance/",
        "/callback/",
        "/cards/",
        "/carts/",
        "/checkout/",
        "/credit_cards/",
        "/login/",
        "/logout/",
        "/orders/",
        "/products/",
        "/profile/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/addresses/": {
      "filePath": "addresses/index.lazy.tsx"
    },
    "/balance/": {
      "filePath": "balance/index.lazy.tsx"
    },
    "/callback/": {
      "filePath": "callback/index.lazy.tsx"
    },
    "/cards/": {
      "filePath": "cards/index.lazy.tsx"
    },
    "/carts/": {
      "filePath": "carts/index.lazy.tsx"
    },
    "/checkout/": {
      "filePath": "checkout/index.lazy.tsx"
    },
    "/credit_cards/": {
      "filePath": "credit_cards/index.lazy.tsx"
    },
    "/login/": {
      "filePath": "login/index.lazy.tsx"
    },
    "/logout/": {
      "filePath": "logout/index.lazy.tsx"
    },
    "/orders/": {
      "filePath": "orders/index.lazy.tsx"
    },
    "/products/": {
      "filePath": "products/index.lazy.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
