/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ProfileIndexLazyImport = createFileRoute('/profile/')()
const ProductsIndexLazyImport = createFileRoute('/products/')()
const LogoutIndexLazyImport = createFileRoute('/logout/')()
const LoginIndexLazyImport = createFileRoute('/login/')()
const CartsIndexLazyImport = createFileRoute('/carts/')()
const CardsIndexLazyImport = createFileRoute('/cards/')()
const CallbackIndexLazyImport = createFileRoute('/callback/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ProfileIndexLazyRoute = ProfileIndexLazyImport.update({
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile/index.lazy').then((d) => d.Route))

const ProductsIndexLazyRoute = ProductsIndexLazyImport.update({
  path: '/products/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/products/index.lazy').then((d) => d.Route),
)

const LogoutIndexLazyRoute = LogoutIndexLazyImport.update({
  path: '/logout/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/logout/index.lazy').then((d) => d.Route))

const LoginIndexLazyRoute = LoginIndexLazyImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))

const CartsIndexLazyRoute = CartsIndexLazyImport.update({
  path: '/carts/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/carts/index.lazy').then((d) => d.Route))

const CardsIndexLazyRoute = CardsIndexLazyImport.update({
  path: '/cards/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cards/index.lazy').then((d) => d.Route))

const CallbackIndexLazyRoute = CallbackIndexLazyImport.update({
  path: '/callback/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/callback/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/callback/': {
      id: '/callback/'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cards/': {
      id: '/cards/'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/carts/': {
      id: '/carts/'
      path: '/carts'
      fullPath: '/carts'
      preLoaderRoute: typeof CartsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/logout/': {
      id: '/logout/'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/callback': typeof CallbackIndexLazyRoute
  '/cards': typeof CardsIndexLazyRoute
  '/carts': typeof CartsIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/logout': typeof LogoutIndexLazyRoute
  '/products': typeof ProductsIndexLazyRoute
  '/profile': typeof ProfileIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/callback': typeof CallbackIndexLazyRoute
  '/cards': typeof CardsIndexLazyRoute
  '/carts': typeof CartsIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/logout': typeof LogoutIndexLazyRoute
  '/products': typeof ProductsIndexLazyRoute
  '/profile': typeof ProfileIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/callback/': typeof CallbackIndexLazyRoute
  '/cards/': typeof CardsIndexLazyRoute
  '/carts/': typeof CartsIndexLazyRoute
  '/login/': typeof LoginIndexLazyRoute
  '/logout/': typeof LogoutIndexLazyRoute
  '/products/': typeof ProductsIndexLazyRoute
  '/profile/': typeof ProfileIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/cards'
    | '/carts'
    | '/login'
    | '/logout'
    | '/products'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/cards'
    | '/carts'
    | '/login'
    | '/logout'
    | '/products'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/callback/'
    | '/cards/'
    | '/carts/'
    | '/login/'
    | '/logout/'
    | '/products/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CallbackIndexLazyRoute: typeof CallbackIndexLazyRoute
  CardsIndexLazyRoute: typeof CardsIndexLazyRoute
  CartsIndexLazyRoute: typeof CartsIndexLazyRoute
  LoginIndexLazyRoute: typeof LoginIndexLazyRoute
  LogoutIndexLazyRoute: typeof LogoutIndexLazyRoute
  ProductsIndexLazyRoute: typeof ProductsIndexLazyRoute
  ProfileIndexLazyRoute: typeof ProfileIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CallbackIndexLazyRoute: CallbackIndexLazyRoute,
  CardsIndexLazyRoute: CardsIndexLazyRoute,
  CartsIndexLazyRoute: CartsIndexLazyRoute,
  LoginIndexLazyRoute: LoginIndexLazyRoute,
  LogoutIndexLazyRoute: LogoutIndexLazyRoute,
  ProductsIndexLazyRoute: ProductsIndexLazyRoute,
  ProfileIndexLazyRoute: ProfileIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/callback/",
        "/cards/",
        "/carts/",
        "/login/",
        "/logout/",
        "/products/",
        "/profile/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/callback/": {
      "filePath": "callback/index.lazy.tsx"
    },
    "/cards/": {
      "filePath": "cards/index.lazy.tsx"
    },
    "/carts/": {
      "filePath": "carts/index.lazy.tsx"
    },
    "/login/": {
      "filePath": "login/index.lazy.tsx"
    },
    "/logout/": {
      "filePath": "logout/index.lazy.tsx"
    },
    "/products/": {
      "filePath": "products/index.lazy.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
